version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - .data.cache:/data
    networks:
      - default

  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery:
    restart: always
    build: .
    container_name: celery
    command: bash -c "celery -A virtual_university worker --beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
    networks:
      - default
volumes:
  postgres_data:
