# Generated by Django 5.0 on 2023-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ссылка на видео'),
        ),
    ]
