# Generated by Django 5.0 on 2023-12-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lesson_options_course_lessons_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
