# Generated by Django 5.0 on 2024-01-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lesson_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lessons',
            new_name='video_link',
        ),
    ]
